export PATH="$HOME/workspace/git/handy/scripts:$PATH"
export PATH="$HOME/workspace/git/shady/scripts:$PATH"
export PATH="/snap/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="/usr/local/opt/node@12/bin:$PATH"
export PATH="/usr/local/opt/influxdb@1/bin:$PATH"
#export PATH="/usr/local/opt/postgresql@9.6/bin:$PATH"
